/*==========================================================*
 * BeyBuilder v1.1 for Dynamite Battle and Burst Ultimate   *
 * Author: Fabel                                            *
 * Copyright 2022-23                                        *
 *==========================================================*/

var blades = [

    //Greatest Rapheal's weight is stored in it's core listing
    {"name":"Astral", "spin":"both", "weight":11.75, "abbv":"A", "wins":0, "losses":0, "draws":0, "id":0},
    {"name":"Burst", "spin":"both", "weight":15.60, "abbv":"Br", "wins":0, "losses":0, "draws":0, "id":1},
    {"name":"Barricade", "spin":"right", "weight":14.80, "abbv":"Brc", "wins":0, "losses":0, "draws":0, "id":2},
    {"name":"Chain", "spin":"right", "weight":14.84, "abbv":"Ch", "wins":0, "losses":0, "draws":0, "id":3},
    {"name":"Cyclone", "spin":"right", "weight":8.30, "abbv":"C", "wins":0, "losses":0, "draws":0, "id":4},
    {"name":"Dangerous", "spin":"right", "weight":10.00, "abbv":"Dn", "wins":0, "losses":0, "draws":0, "id":5},
    {"name":"Dangerous F", "spin":"right", "weight":15.21, "abbv":"Dn+F", "wins":0, "losses":0, "draws":0, "id":6},
    {"name":"Devil", "spin":"right", "weight":5.32, "abbv":"Dv", "wins":0, "losses":0, "draws":0, "id":7},
    {"name":"Devil F", "spin":"right", "weight":10.73, "abbv":"Dv+F", "wins":0, "losses":0, "draws":0, "id":8},
    {"name":"Divine", "spin":"right", "weight":9.36, "abbv":"Dvn", "wins":0, "losses":0, "draws":0, "id":9},
    {"name":"Divine A", "spin":"right", "weight":13.69, "abbv":"Dvn+A", "wins":0, "losses":0, "draws":0, "id":10},
    {"name":"Divine F", "spin":"right", "weight":14.76, "abbv":"Dvn+F", "wins":0, "losses":0, "draws":0, "id":11},
    {"name":"Dynamite", "spin":"right", "weight":5.50, "abbv":"D", "wins":0, "losses":0, "draws":0, "id":12},
    {"name":"Dynamite F", "spin":"right", "weight":10.71, "abbv":"D+F", "wins":0, "losses":0, "draws":0, "id":13},
    {"name":"Gatling", "spin":"right", "weight":16.20, "abbv":"Gt", "wins":0, "losses":0, "draws":0, "id":14},
    {"name":"Greatest Rapheal", "spin":"right", "weight":0, "abbv":"", "wins":0, "losses":0, "draws":0, "id":15},
    {"name":"Guilty", "spin":"left", "weight":17.06, "abbv":"G", "wins":0, "losses":0, "draws":0, "id":16},
    {"name":"King M", "spin":"both", "weight":16.00, "abbv":"K M", "wins":0, "losses":0, "draws":0, "id":17},
    {"name":"King MR", "spin":"both", "weight":15.80, "abbv":"K MR", "wins":0, "losses":0, "draws":0, "id":18},
    {"name":"King R", "spin":"both", "weight":15.60, "abbv":"K R", "wins":0, "losses":0, "draws":0, "id":19},
    {"name":"Prominance", "spin":"right", "weight":14.71, "abbv":"P", "wins":0, "losses":0, "draws":0, "id":20},
    {"name":"Roar", "spin":"left", "weight":12.10, "abbv":"R", "wins":0, "losses":0, "draws":0, "id":21},
    {"name":"Savior", "spin":"right", "weight":10.82, "abbv":"S", "wins":0, "losses":0, "draws":0, "id":22},
    {"name":"Super M", "spin":"both", "weight":15.80, "abbv":"S M", "wins":0, "losses":0, "draws":0, "id":23},
    {"name":"Super MR", "spin":"both", "weight":15.73, "abbv":"S MR", "wins":0, "losses":0, "draws":0, "id":24},
    {"name":"Super R", "spin":"both", "weight":15.40, "abbv":"S R", "wins":0, "losses":0, "draws":0, "id":25},
    {"name":"SuperKing M", "spin":"both", "weight":15.89, "abbv":"SK M", "wins":0, "losses":0, "draws":0, "id":26},
    {"name":"SuperKing MR", "spin":"both", "weight":15.70, "abbv":"SK MR", "wins":0, "losses":0, "draws":0, "id":27},
    {"name":"SuperKing R", "spin":"both", "weight":15.53, "abbv":"SK R", "wins":0, "losses":0, "draws":0, "id":28},
    {"name":"SuperKing RM", "spin":"both", "weight":15.70, "abbv":"SK RM", "wins":0, "losses":0, "draws":0, "id":29},
    {"name":"Ultimate", "spin":"right", "weight":11.20, "abbv":"U", "wins":0, "losses":0, "draws":0, "id":30},
    {"name":"Vanish", "spin":"left", "weight":12.50, "abbv":"V", "wins":0, "losses":0, "draws":0, "id":31},
    {"name":"Wind", "spin":"right", "weight":13.05, "abbv":"Wn", "wins":0, "losses":0, "draws":0, "id":32},
    {"name":"Xiphiod", "spin":"right", "weight":13.00, "abbv":"Xp", "wins":0, "losses":0, "draws":0, "id":33},
    {"name":"Zest Attack L", "spin":"left", "weight":10.00, "abbv":"Zs", "wins":0, "losses":0, "draws":0, "id":34},
    {"name":"Zest Attack R", "spin":"right", "weight":10.00, "abbv":"Zs", "wins":0, "losses":0, "draws":0, "id":35},
    {"name":"Zest Defence L", "spin":"left", "weight":10.00, "abbv":"Zs", "wins":0, "losses":0, "draws":0, "id":36},
    {"name":"Zest Defence R", "spin":"right", "weight":10.00, "abbv":"Zs", "wins":0, "losses":0, "draws":0, "id":37},
    {"name":"Zest Speed L", "spin":"left", "weight":6.00, "abbv":"Zs", "wins":0, "losses":0, "draws":0, "id":38},
    {"name":"Zest Speed R", "spin":"right", "weight":6.00, "abbv":"Zs", "wins":0, "losses":0, "draws":0, "id":39}
    
];

var cores = [

    //Lucifer isn't out yet, we don't know it's weight, so it's listed as 0 for now
    {"name":"Achilles", "spin":"both", "weight":8.09, "abbv":"AC", "wins":0, "losses":0, "draws":0, "id":0},
    {"name":"Bahamut", "spin":"left", "weight":7.80, "abbv":"Bahamut", "wins":0, "losses":0, "draws":0, "id":1},
    {"name":"Belial", "spin":"right", "weight":7.00, "abbv":"BL", "wins":0, "losses":0, "draws":0, "id":2},
    {"name":"Belial 2", "spin":"right", "weight":8.10, "abbv":"BL2", "wins":0, "losses":0, "draws":0, "id":3},
    {"name":"Belial 3", "spin":"right", "weight":9.36, "abbv":"BL3", "wins":0, "losses":0, "draws":0, "id":4},
    {"name":"Dragon", "spin":"right", "weight":7.80, "abbv":"Dragon", "wins":0, "losses":0, "draws":0, "id":5},
    {"name":"Fafnir", "spin":"left", "weight":7.21, "abbv":"FF", "wins":0, "losses":0, "draws":0, "id":6},
    {"name":"Greatest Rapheal", "spin":"right", "weight":30.70, "abbv":"GRP", "wins":0, "losses":0, "draws":0, "id":7},
    {"name":"Helios", "spin":"left", "weight":7.18, "abbv":"HL", "wins":0, "losses":0, "draws":0, "id":8},
    {"name":"Hello Kitty", "spin":"both", "weight":7.44, "abbv":"HK", "wins":0, "losses":0, "draws":0, "id":9},
    {"name":"Hyperion", "spin":"right", "weight":7.44, "abbv":"HY", "wins":0, "losses":0, "draws":0, "id":10},
    {"name":"Kerbeus", "spin":"right", "weight":8.05, "abbv":"KR", "wins":0, "losses":0, "draws":0, "id":11},
    {"name":"Knight", "spin":"right", "weight":7.62, "abbv":"KN", "wins":0, "losses":0, "draws":0, "id":12},
    {"name":"Loginus", "spin":"left", "weight":10.08, "abbv":"LN", "wins":0, "losses":0, "draws":0, "id":13},
    {"name":"Lucifer", "spin":"right", "weight":7.20, "abbv":"LC", "wins":0, "losses":0, "draws":0, "id":14},
    {"name":"Perseus", "spin":"right", "weight":10.70, "abbv":"PR", "wins":0, "losses":0, "draws":0, "id":15},
    {"name":"Pheonix", "spin":"right", "weight":7.45, "abbv":"PH", "wins":0, "losses":0, "draws":0, "id":16},
    {"name":"Ragnaruk", "spin":"right", "weight":6.70, "abbv":"RG", "wins":0, "losses":0, "draws":0, "id":17},
    {"name":"Spriggan", "spin":"both", "weight":7.90, "abbv":"SP", "wins":0, "losses":0, "draws":0, "id":18},
    {"name":"Spriggan 2", "spin":"both", "weight":7.45, "abbv":"SP2", "wins":0, "losses":0, "draws":0, "id":19},
    {"name":"Valkyrie", "spin":"right", "weight":7.86, "abbv":"VL", "wins":0, "losses":0, "draws":0, "id":20},
    {"name":"Valkyrie 2", "spin":"right", "weight":7.50, "abbv":"VL2", "wins":0, "losses":0, "draws":0, "id":21},
    {"name":"Xcalibur", "spin":"right", "weight":10.47, "abbv":"XC", "wins":0, "losses":0, "draws":0, "id":22}
    
];

var forgeDiscs = [

    //All Might and Shot have their weights stored in their driver listings
    {"name":"All Might", "weight":0, "abbv":"Al", "wins":0, "losses":0, "draws":0, "id":0},
    {"name":"All Might+V", "weight":0, "abbv":"Al+V", "wins":0, "losses":0, "draws":0, "id":1},
    {"name":"All Might+S", "weight":0, "abbv":"Al+S", "wins":0, "losses":0, "draws":0, "id":2},
    {"name":"All Might+D", "weight":0, "abbv":"Al+D", "wins":0, "losses":0, "draws":0, "id":3},
    {"name":"All Might+SV", "weight":0, "abbv":"Al+SV", "wins":0, "losses":0, "draws":0, "id":4},
    {"name":"All Might+DV", "weight":0, "abbv":"Al+DV", "wins":0, "losses":0, "draws":0, "id":5},
    {"name":"Fortress", "weight":31.04, "abbv":"Ft", "wins":0, "losses":0, "draws":0, "id":6},
    {"name":"Generate", "weight":0, "abbv":"Gn", "wins":0, "losses":0, "draws":0, "id":7},
    {"name":"Giga", "weight":32.41, "abbv":"Gg", "wins":0, "losses":0, "draws":0, "id":8},
    {"name":"Hybrid", "weight":0, "abbv":"Hy", "wins":0, "losses":0, "draws":0, "id":9},
    {"name":"Ignition'", "weight":0, "abbv":"Ig'", "wins":0, "losses":0, "draws":0, "id":10},
    {"name":"Illegal", "weight":31.82, "abbv":"Il", "wins":0, "losses":0, "draws":0, "id":11},
    {"name":"Karma", "weight":23.20, "abbv":"Kr", "wins":0, "losses":0, "draws":0, "id":12},
    {"name":"Legacy", "weight":30.30, "abbv":"Lg", "wins":0, "losses":0, "draws":0, "id":13},
    {"name":"Moon", "weight":31.50, "abbv":"Mn", "wins":0, "losses":0, "draws":0, "id":14},
    {"name":"Mugen", "weight":0, "abbv":"∞", "wins":0, "losses":0, "draws":0, "id":15},
    {"name":"Mugen-L", "weight":0, "abbv":"∞L", "wins":0, "losses":0, "draws":0, "id":16},
    {"name":"Nexus", "weight":30.73, "abbv":"Nx", "wins":0, "losses":0, "draws":0, "id":17},
    {"name":"Nexus+D", "weight":34.67, "abbv":"Nx+D", "wins":0, "losses":0, "draws":0, "id":18},
    {"name":"Nexus+S", "weight":35.05, "abbv":"Nx+S", "wins":0, "losses":0, "draws":0, "id":19},
    {"name":"Over", "weight":33.48, "abbv":"Ov", "wins":0, "losses":0, "draws":0, "id":20},
    {"name":"Shot", "weight":0, "abbv":"Sh", "wins":0, "losses":0, "draws":0, "id":21},
    {"name":"Spread'", "weight":33.00, "abbv":"S'", "wins":0, "losses":0, "draws":0, "id":22},
    {"name":"Tapered", "weight":28.83, "abbv":"Tp", "wins":0, "losses":0, "draws":0, "id":23},
    {"name":"Wing'", "weight":31.90, "abbv":"W'", "wins":0, "losses":0, "draws":0, "id":24},
    {"name":"Xanthas", "weight":32.48, "abbv":"Xn", "wins":0, "losses":0, "draws":0, "id":25}
    
    
];

var drivers = [

    {"name":"Absorb", "weight":6.84, "abbv":"Ab", "wins":0, "losses":0, "draws":0, "id":0},
    {"name":"Accel", "weight":5.67, "abbv":"A", "wins":0, "losses":0, "draws":0, "id":1},
    {"name":"Accel'", "weight":5.85, "abbv":"A'", "wins":0, "losses":0, "draws":0, "id":2},
    {"name":"High Accel'", "weight":7.22, "abbv":"HA'", "wins":0, "losses":0, "draws":0, "id":3},
    {"name":"Metal Accel", "weight":7.83, "abbv":"MA", "wins":0, "losses":0, "draws":0, "id":4},
    {"name":"Adventure", "weight":8.10, "abbv":"Ad", "wins":0, "losses":0, "draws":0, "id":5},
    {"name":"Adventure+V", "weight":13.67, "abbv":"Ad+V", "wins":0, "losses":0, "draws":0, "id":6},
    {"name":"Adventure+VS", "weight":15.66, "abbv":"Ad+VS", "wins":0, "losses":0, "draws":0, "id":7},
    {"name":"All Might", "weight":38.02, "abbv":"", "wins":0, "losses":0, "draws":0, "id":8},
    {"name":"All Might+V", "weight":43.59, "abbv":"", "wins":0, "losses":0, "draws":0, "id":9},
    {"name":"All Might+S", "weight":42.32, "abbv":"", "wins":0, "losses":0, "draws":0, "id":10},
    {"name":"All Might+D", "weight":41.96, "abbv":"", "wins":0, "losses":0, "draws":0, "id":11},
    {"name":"All Might+SV", "weight":47.89, "abbv":"", "wins":0, "losses":0, "draws":0, "id":12},
    {"name":"All Might+DV", "weight":47.53, "abbv":"", "wins":0, "losses":0, "draws":0, "id":13},
    {"name":"Anchor", "weight":6.85, "abbv":"αn", "wins":0, "losses":0, "draws":0, "id":14},
    {"name":"Assault", "weight":5.65, "abbv":"α", "wins":0, "losses":0, "draws":0, "id":15},
    {"name":"Assault'", "weight":5.78, "abbv":"α'", "wins":0, "losses":0, "draws":0, "id":16},
    {"name":"Atomic", "weight":7.30, "abbv":"At", "wins":0, "losses":0, "draws":0, "id":17},
    {"name":"Atomic'", "weight":7.55, "abbv":"At'", "wins":0, "losses":0, "draws":0, "id":18},
    {"name":"Bearing", "weight":6.26, "abbv":"Br", "wins":0, "losses":0, "draws":0, "id":19},
    {"name":"Bearing'", "weight":6.42, "abbv":"Br'", "wins":0, "losses":0, "draws":0, "id":20},
    {"name":"Bite", "weight":5.89, "abbv":"ß", "wins":0, "losses":0, "draws":0, "id":21},
    {"name":"Blow", "weight":5.50, "abbv":"B", "wins":0, "losses":0, "draws":0, "id":22},
    {"name":"Blow'", "weight":5.73, "abbv":"B'", "wins":0, "losses":0, "draws":0, "id":23},
    {"name":"High Blow'", "weight":7.11, "abbv":"HB'", "wins":0, "losses":0, "draws":0, "id":24},
    {"name":"Bounce", "weight":6.66, "abbv":"Bn", "wins":0, "losses":0, "draws":0, "id":25},
    {"name":"Bullet", "weight":15.29, "abbv":"Bl", "wins":0, "losses":0, "draws":0, "id":26},
    {"name":"Charge", "weight":14.79, "abbv":"Ch", "wins":0, "losses":0, "draws":0, "id":27},
    {"name":"Charge'", "weight":15.20, "abbv":"Ch'", "wins":0, "losses":0, "draws":0, "id":28},
    {"name":"Charge Metal", "weight":16.29, "abbv":"Cm", "wins":0, "losses":0, "draws":0, "id":29},
    {"name":"Charge Metal'", "weight":16.15, "abbv":"Cm'", "wins":0, "losses":0, "draws":0, "id":30},
    {"name":"High Charge'", "weight":16.74, "abbv":"HCh", "wins":0, "losses":0, "draws":0, "id":31},
    {"name":"Claw", "weight":6.49, "abbv":"C", "wins":0, "losses":0, "draws":0, "id":32},
    {"name":"Cycle", "weight":7.12, "abbv":"Cy", "wins":0, "losses":0, "draws":0, "id":33},
    {"name":"Defense", "weight":6.22, "abbv":"D", "wins":0, "losses":0, "draws":0, "id":34},
    {"name":"High Defense", "weight":7.46, "abbv":"HD", "wins":0, "losses":0, "draws":0, "id":35},
    {"name":"Metal Defense", "weight":8.35, "abbv":"MD", "wins":0, "losses":0, "draws":0, "id":36},
    {"name":"Destroy", "weight":6.55, "abbv":"Ds", "wins":0, "losses":0, "draws":0, "id":37},
    {"name":"Destroy'", "weight":6.81, "abbv":"Ds'", "wins":0, "losses":0, "draws":0, "id":38},
    {"name":"Metal Destroy", "weight":8.82, "abbv":"MDs", "wins":0, "losses":0, "draws":0, "id":39},
    {"name":"Dimension", "weight":7.22, "abbv":"Dm", "wins":0, "losses":0, "draws":0, "id":40},
    {"name":"Dimension'", "weight":7.34, "abbv":"Dm'", "wins":0, "losses":0, "draws":0, "id":41},
    {"name":"Metal Dimension", "weight":9.20, "abbv":"MDm", "wins":0, "losses":0, "draws":0, "id":42},
    {"name":"Drift", "weight":10.01, "abbv":"Dr", "wins":0, "losses":0, "draws":0, "id":43},
    {"name":"Bearing Drift", "weight":10.18, "abbv":"BDr", "wins":0, "losses":0, "draws":0, "id":44},
    {"name":"Metal Drift", "weight":12.05, "abbv":"MDr", "wins":0, "losses":0, "draws":0, "id":45},
    {"name":"Metal Bearing Drift", "weight":12.35, "abbv":"MBDr", "wins":0, "losses":0, "draws":0, "id":46},
    {"name":"Edge", "weight":5.51, "abbv":"E", "wins":0, "losses":0, "draws":0, "id":47},
    {"name":"Eternal", "weight":6.01, "abbv":"Et", "wins":0, "losses":0, "draws":0, "id":48},
    {"name":"High Eternal", "weight":7.63, "abbv":"HEt", "wins":0, "losses":0, "draws":0, "id":49},
    {"name":"Evolution", "weight":6.45, "abbv":"Ev", "wins":0, "losses":0, "draws":0, "id":50},
    {"name":"Evolution'", "weight":6.62, "abbv":"Ev'", "wins":0, "losses":0, "draws":0, "id":51},
    {"name":"Flugel", "weight":5.79, "abbv":"Fl", "wins":0, "losses":0, "draws":0, "id":52},
    {"name":"Friction", "weight":6.50, "abbv":"Fr", "wins":0, "losses":0, "draws":0, "id":53},
    {"name":"Fusion", "weight":5.66, "abbv":"F", "wins":0, "losses":0, "draws":0, "id":54},
    {"name":"Fusion'", "weight":5.73, "abbv":"F'", "wins":0, "losses":0, "draws":0, "id":55},
    {"name":"Metal Fusion", "weight":7.69, "abbv":"MF", "wins":0, "losses":0, "draws":0, "id":56},
    {"name":"Generate", "weight":36.70, "abbv":"", "wins":0, "losses":0, "draws":0, "id":57},
    {"name":"Guard", "weight":6.54, "abbv":"Gr", "wins":0, "losses":0, "draws":0, "id":58},
    {"name":"Gyro", "weight":5.76, "abbv":"G", "wins":0, "losses":0, "draws":0, "id":59},
    {"name":"Hold", "weight":6.50, "abbv":"H", "wins":0, "losses":0, "draws":0, "id":60},
    {"name":"Hold'", "weight":6.84, "abbv":"H'", "wins":0, "losses":0, "draws":0, "id":61},
    {"name":"High Hold'", "weight":8.31, "abbv":"HH'", "wins":0, "losses":0, "draws":0, "id":62},
    {"name":"Hunter", "weight":5.86, "abbv":"Hn", "wins":0, "losses":0, "draws":0, "id":63},
    {"name":"Hunter'", "weight":6.04, "abbv":"Hn'", "wins":0, "losses":0, "draws":0, "id":64},
    {"name":"Hybrid", "weight":38.63, "abbv":"", "wins":0, "losses":0, "draws":0, "id":65},
    {"name":"Ignition'", "weight":39.10, "abbv":"", "wins":0, "losses":0, "draws":0, "id":66}, 
    {"name":"Impact", "weight":5.93, "abbv":"I", "wins":0, "losses":0, "draws":0, "id":67},
    {"name":"Iron", "weight":6.93, "abbv":"Ir", "wins":0, "losses":0, "draws":0, "id":68},
    {"name":"Jaggy", "weight":5.78, "abbv":"J", "wins":0, "losses":0, "draws":0, "id":69},
    {"name":"Jaggy'", "weight":5.94, "abbv":"J'", "wins":0, "losses":0, "draws":0, "id":70},
    {"name":"High Jaggy'", "weight":7.34, "abbv":"HJ'", "wins":0, "losses":0, "draws":0, "id":71},
    {"name":"Jolt", "weight":6.02, "abbv":"Jl", "wins":0, "losses":0, "draws":0, "id":72},
    {"name":"Jolt'", "weight":6.26, "abbv":"Jl'", "wins":0, "losses":0, "draws":0, "id":73},
    {"name":"Just", "weight":7.74, "abbv":"Js'", "wins":0, "losses":0, "draws":0, "id":74},
    {"name":"Just'", "weight":8.00, "abbv":"Js'", "wins":0, "losses":0, "draws":0, "id":75},
    {"name":"Keep", "weight":6.48, "abbv":"Kp", "wins":0, "losses":0, "draws":0, "id":76},
    {"name":"Keep'", "weight":6.66, "abbv":"Kp'", "wins":0, "losses":0, "draws":0, "id":77},
    {"name":"Kick", "weight":9.40, "abbv":"Kc", "wins":0, "losses":0, "draws":0, "id":78},
    {"name":"Liner", "weight":5.64, "abbv":"L", "wins":0, "losses":0, "draws":0, "id":79},
    {"name":"Liner'", "weight":6.00, "abbv":"L'", "wins":0, "losses":0, "draws":0, "id":80},
    {"name":"Loop", "weight":6.06, "abbv":"Lp", "wins":0, "losses":0, "draws":0, "id":81},
    {"name":"Low", "weight":9.45, "abbv":"Lw", "wins":0, "losses":0, "draws":0, "id":82},
    {"name":"Massive", "weight":5.54, "abbv":"M", "wins":0, "losses":0, "draws":0, "id":83},
    {"name":"High Massive", "weight":7.04, "abbv":"HM", "wins":0, "losses":0, "draws":0, "id":84},
    {"name":"Merge", "weight":5.95, "abbv":"Mr", "wins":0, "losses":0, "draws":0, "id":85},
    {"name":"Merge'", "weight":6.63, "abbv":"Mr'", "wins":0, "losses":0, "draws":0, "id":86},
    {"name":"Mobius", "weight":7.71, "abbv":"Mb", "wins":0, "losses":0, "draws":0, "id":87},
    {"name":"Bearing Mobius", "weight":7.82, "abbv":"BMb", "wins":0, "losses":0, "draws":0, "id":88},
    {"name":"Moment", "weight":7.22, "abbv":"Mm", "wins":0, "losses":0, "draws":0, "id":89},
    {"name":"Moment'", "weight":7.39, "abbv":"Mm'", "wins":0, "losses":0, "draws":0, "id":90},
    {"name":"Mugen", "weight":35.26, "abbv":"", "wins":0, "losses":0, "draws":0, "id":91},
    {"name":"Mugen-L", "weight":34.93, "abbv":"", "wins":0, "losses":0, "draws":0, "id":92},
    {"name":"Needle", "weight":5.54, "abbv":"N", "wins":0, "losses":0, "draws":0, "id":93},
    {"name":"Never", "weight":7.58, "abbv":"Nv", "wins":0, "losses":0, "draws":0, "id":94},
    {"name":"Metal Never", "weight":9.69, "abbv":"MNv", "wins":0, "losses":0, "draws":0, "id":95},
    {"name":"Nothing", "weight":6.22, "abbv":"Nt", "wins":0, "losses":0, "draws":0, "id":96},
    {"name":"Octa", "weight":14.14, "abbv":"Ω", "wins":0, "losses":0, "draws":0, "id":97},
    {"name":"Operate", "weight":7.06, "abbv":"Op", "wins":0, "losses":0, "draws":0, "id":98},
    {"name":"Operate'", "weight":7.27, "abbv":"Op'", "wins":0, "losses":0, "draws":0, "id":99},
    {"name":"Orbit", "weight":6.04, "abbv":"O", "wins":0, "losses":0, "draws":0, "id":100},
    {"name":"Orbit Metal", "weight":7.89, "abbv":"Om", "wins":0, "losses":0, "draws":0, "id":101},
    {"name":"Planet", "weight":9.26, "abbv":"Pl", "wins":0, "losses":0, "draws":0, "id":102},
    {"name":"Planet'", "weight":9.46, "abbv":"Pl'", "wins":0, "losses":0, "draws":0, "id":103},
    {"name":"Power", "weight":6.51, "abbv":"Pw", "wins":0, "losses":0, "draws":0, "id":104},
    {"name":"Press", "weight":6.40, "abbv":"P", "wins":0, "losses":0, "draws":0, "id":105},
    {"name":"Quake", "weight":5.42, "abbv":"Q", "wins":0, "losses":0, "draws":0, "id":106},
    {"name":"Quake'", "weight":5.59, "abbv":"Q'", "wins":0, "losses":0, "draws":0, "id":107},
    {"name":"Quattro", "weight":10.53, "abbv":"Qt", "wins":0, "losses":0, "draws":0, "id":108},
    {"name":"Quattro'", "weight":10.71, "abbv":"Qt'", "wins":0, "losses":0, "draws":0, "id":109},
    {"name":"Quest", "weight":7.32, "abbv":"Qs", "wins":0, "losses":0, "draws":0, "id":110},
    {"name":"Quick", "weight":5.60, "abbv":"Qc", "wins":0, "losses":0, "draws":0, "id":111},
    {"name":"Quick'", "weight":5.79, "abbv":"Qc'", "wins":0, "losses":0, "draws":0, "id":112},
    {"name":"Reboot", "weight":7.55, "abbv":"Rb", "wins":0, "losses":0, "draws":0, "id":113},
    {"name":"Reboot'", "weight":7.74, "abbv":"Rb'", "wins":0, "losses":0, "draws":0, "id":114},
    {"name":"Revolve", "weight":5.82, "abbv":"R", "wins":0, "losses":0, "draws":0, "id":115},
    {"name":"Revolve'", "weight":5.95, "abbv":"R'", "wins":0, "losses":0, "draws":0, "id":116},
    {"name":"High Revolve", "weight":7.20, "abbv":"HR", "wins":0, "losses":0, "draws":0, "id":117},
    {"name":"Rise", "weight":6.12, "abbv":"Rs", "wins":0, "losses":0, "draws":0, "id":118},
    {"name":"Shot", "weight":42.26, "abbv":"", "wins":0, "losses":0, "draws":0, "id":119},
    {"name":"Spiral", "weight":6.04, "abbv":"Sp", "wins":0, "losses":0, "draws":0, "id":120},
    {"name":"Sprial'", "weight":6.24, "abbv":"Sp'", "wins":0, "losses":0, "draws":0, "id":121},
    {"name":"Survive", "weight":5.66, "abbv":"S", "wins":0, "losses":0, "draws":0, "id":122},
    {"name":"High Survive", "weight":7.03, "abbv":"HS", "wins":0, "losses":0, "draws":0, "id":123},
    {"name":"Metal Survive", "weight":7.75, "abbv":"MS", "wins":0, "losses":0, "draws":0, "id":124},
    {"name":"Sword", "weight":9.12, "abbv":"Sw", "wins":0, "losses":0, "draws":0, "id":125},
    {"name":"Sword'", "weight":9.28, "abbv":"Sw'", "wins":0, "losses":0, "draws":0, "id":126},
    {"name":"Tower", "weight":8.55, "abbv":"Tw", "wins":0, "losses":0, "draws":0, "id":127},
    {"name":"Trans", "weight":6.56, "abbv":"T", "wins":0, "losses":0, "draws":0, "id":128},
    {"name":"Trans'", "weight":6.62, "abbv":"T'", "wins":0, "losses":0, "draws":0, "id":129},
    {"name":"Trick", "weight":9.95, "abbv":"Tr", "wins":0, "losses":0, "draws":0, "id":130},
    {"name":"Ultimate Reboot", "weight":8.22, "abbv":"Ul", "wins":0, "losses":0, "draws":0, "id":131},
    {"name":"Ultimate Reboot'", "weight":8.30, "abbv":"Ul'", "wins":0, "losses":0, "draws":0, "id":132},
    {"name":"Unite", "weight":5.83, "abbv":"U", "wins":0, "losses":0, "draws":0, "id":133},
    {"name":"Unite'", "weight":6.11, "abbv":"U'", "wins":0, "losses":0, "draws":0, "id":134},
    {"name":"Universe", "weight":8.76, "abbv":"Un", "wins":0, "losses":0, "draws":0, "id":135},
    {"name":"Metal Universe", "weight":10.90, "abbv":"MUn", "wins":0, "losses":0, "draws":0, "id":136},
    {"name":"Variable", "weight":6.19, "abbv":"V", "wins":0, "losses":0, "draws":0, "id":137},
    {"name":"Variable'", "weight":6.38, "abbv":"V'", "wins":0, "losses":0, "draws":0, "id":138},
    {"name":"Venture", "weight":7.77, "abbv":"Vn", "wins":0, "losses":0, "draws":0, "id":139},
    {"name":"Venture+V", "weight":13.34, "abbv":"Vn+V", "wins":0, "losses":0, "draws":0, "id":140},
    {"name":"Venture+VS", "weight":15.33, "abbv":"Vn+VS", "wins":0, "losses":0, "draws":0, "id":141},
    {"name":"Volcanic", "weight":6.36, "abbv":"Vl", "wins":0, "losses":0, "draws":0, "id":142},
    {"name":"Volcanic'", "weight":6.52, "abbv":"Vl'", "wins":0, "losses":0, "draws":0, "id":143},
    {"name":"Wave", "weight":8.18, "abbv":"Wv", "wins":0, "losses":0, "draws":0, "id":145},
    {"name":"Wave'", "weight":8.54, "abbv":"Wv'", "wins":0, "losses":0, "draws":0, "id":146},
    {"name":"High Wave'", "weight":9.83, "abbv":"HWv'", "wins":0, "losses":0, "draws":0, "id":147},
    {"name":"Wedge", "weight":7.06, "abbv":"Wd", "wins":0, "losses":0, "draws":0, "id":148},
    {"name":"Wedge'", "weight":7.21, "abbv":"Wd'", "wins":0, "losses":0, "draws":0, "id":149},
    {"name":"Weight", "weight":6.50, "abbv":"W", "wins":0, "losses":0, "draws":0, "id":150},
    {"name":"Xceed", "weight":6.02, "abbv":"Xc", "wins":0, "losses":0, "draws":0, "id":151},
    {"name":"Xceed'", "weight":6.23, "abbv":"Xc'", "wins":0, "losses":0, "draws":0, "id":152},
    {"name":"Xceed+X", "weight":10.32, "abbv":"Xc+X", "wins":0, "losses":0, "draws":0, "id":153},
    {"name":"Xceed+Z", "weight":8.70, "abbv":"Xc+Z", "wins":0, "losses":0, "draws":0, "id":154},
    {"name":"Xceed'+X", "weight":10.53, "abbv":"Xc'+X", "wins":0, "losses":0, "draws":0, "id":155},
    {"name":"Xceed'+Z", "weight":8.91, "abbv":"Xc'+Z", "wins":0, "losses":0, "draws":0, "id":156},
    {"name":"Xplosion", "weight":6.57, "abbv":"Xp", "wins":0, "losses":0, "draws":0, "id":157},
    {"name":"Xplosion'", "weight":6.40, "abbv":"Xp'", "wins":0, "losses":0, "draws":0, "id":158},
    {"name":"Xtend", "weight":7.62, "abbv":"Xt", "wins":0, "losses":0, "draws":0, "id":159},
    {"name":"Xtend+", "weight":7.76, "abbv":"Xt+", "wins":0, "losses":0, "draws":0, "id":160},
    {"name":"High Xtend'", "weight":9.14, "abbv":"HXt'", "wins":0, "losses":0, "draws":0, "id":161},
    {"name":"High Xtend+'", "weight":9.30, "abbv":"HXt+'", "wins":0, "losses":0, "draws":0, "id":162},
    {"name":"Xtreme", "weight":5.27, "abbv":"X", "wins":0, "losses":0, "draws":0, "id":163},
    {"name":"Xtreme'", "weight":5.55, "abbv":"X'", "wins":0, "losses":0, "draws":0, "id":164},
    {"name":"Metal Xtreme", "weight":7.40, "abbv":"MX", "wins":0, "losses":0, "draws":0, "id":165},
    {"name":"Xplosion", "weight":6.69, "abbv":"Xp", "wins":0, "losses":0, "draws":0, "id":166},
    {"name":"Xplosion'", "weight":0, "abbv":"Xp'", "wins":0, "losses":0, "draws":0, "id":167},
    {"name":"Yard", "weight":7.14, "abbv":"Yr", "wins":0, "losses":0, "draws":0, "id":168},
    {"name":"Yard'", "weight":7.37, "abbv":"Yd'", "wins":0, "losses":0, "draws":0, "id":169},
    {"name":"Yard Metal", "weight":8.96, "abbv":"Ym", "wins":0, "losses":0, "draws":0, "id":170},
    {"name":"Yielding", "weight":5.55, "abbv":"Y", "wins":0, "losses":0, "draws":0, "id":171},
    {"name":"Zeal", "weight":6.55, "abbv":"Zl", "wins":0, "losses":0, "draws":0, "id":172},
    {"name":"Zephyr", "weight":5.41, "abbv":"Z", "wins":0, "losses":0, "draws":0, "id":173},
    {"name":"Zephyr'", "weight":5.63, "abbv":"Z'", "wins":0, "losses":0, "draws":0, "id":174},
    {"name":"High Zephyr", "weight":6.86, "abbv":"HZ", "wins":0, "losses":0, "draws":0, "id":175},
    {"name":"Zeta", "weight":6.05, "abbv":"Zt", "wins":0, "losses":0, "draws":0, "id":176},
    {"name":"Zeta'", "weight":6.26, "abbv":"Zt'", "wins":0, "losses":0, "draws":0, "id":177},
    {"name":"Zone", "weight":6.00, "abbv":"Zn", "wins":0, "losses":0, "draws":0, "id":178},
    {"name":"Zone'", "weight":6.10, "abbv":"Zn'", "wins":0, "losses":0, "draws":0, "id":179},
    {"name":"Zone+X", "weight":10.30, "abbv":"Zn+X", "wins":0, "losses":0, "draws":0, "id":180},
    {"name":"Zone+Z", "weight":8.68, "abbv":"Zn+Z", "wins":0, "losses":0, "draws":0, "id":181},
    {"name":"Zone'+X", "weight":10.40, "abbv":"Zn'+X", "wins":0, "losses":0, "draws":0, "id":182},
    {"name":"Zone'+Z", "weight":8.78, "abbv":"Zn'+Z", "wins":0, "losses":0, "draws":0, "id":183}    

];

var armors = [

    //Greatest Rapheal's weight is stored in it's core listing
    {"name":"0", "weight":13.89, "abbv":"0", "wins":0, "losses":0, "draws":0, "id":0},
    {"name":"1", "weight":13.09, "abbv":"1", "wins":0, "losses":0, "draws":0, "id":1},
    {"name":"2", "weight":13.47, "abbv":"2", "wins":0, "losses":0, "draws":0, "id":2},
    {"name":"3", "weight":13.22, "abbv":"3", "wins":0, "losses":0, "draws":0, "id":3},
    {"name":"4", "weight":13.96, "abbv":"4", "wins":0, "losses":0, "draws":0, "id":4},
    {"name":"6", "weight":13.31, "abbv":"6", "wins":0, "losses":0, "draws":0, "id":5},
    {"name":"7", "weight":13.41, "abbv":"7", "wins":0, "losses":0, "draws":0, "id":6},
    {"name":"8", "weight":13.00, "abbv":"8", "wins":0, "losses":0, "draws":0, "id":7},
    {"name":"9", "weight":13.90, "abbv":"9", "wins":0, "losses":0, "draws":0, "id":8},
    {"name":"10", "weight":13.25, "abbv":"10", "wins":0, "losses":0, "draws":0, "id":9},
    {"name":"L Gear", "weight":13.25, "abbv":"L", "wins":0, "losses":0, "draws":0, "id":10},
    {"name":"H Gear", "weight":13.25, "abbv":"H", "wins":0, "losses":0, "draws":0, "id":11},
    {"name":"Greatest Rapheal", "weight":0, "abbv":"", "wins":0, "losses":0, "draws":0, "id":12}

];